spring:
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
    url:  jdbc:mysql://localhost:3306/shiro-test?useUnicode=true&characterEncoding=utf8
    password: root
    username: root
    druid:
      initialSize: 5
      minIdle: 5
      maxActive: 20
      maxWait: 6000
      filters: stat,wall,log4j



server:
  port:  8888
logging:
  config: classpath:log4j2.xml

mybatis:
  mapperLocations: classpath:mybatis/*.xml
  typeAliasesPackage: com.xyj.shiro.domain
