spring:
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
    url:  jdbc:mysql://localhost:3306/test?useUnicode=true?characterEncoding=utf8
    password: root
    username: root
    max-active: 20
    max-idle: 8
    min-idle: 8

server:
  port:  8888
#logging:
 # config: classpath:log4j2.xml
