spring:
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
    url:  jdbc:mysql://localhost:3306/shiro-test?useUnicode=true&characterEncoding=utf8
    password: root
    username: root
    druid:
      initialSize: 5
      minIdle: 5
      maxActive: 20
      maxWait: 6000
      filters: stat,wall,log4j
  #日志颜色的问题
  output:
    ansi:
      enabled: detect



server:
  port:  8889

logging:
  config: classpath:log4j.properties

mybatis:
  mapperLocations: classpath:mybatis/*.xml
  typeAliasesPackage: com.xyj.shiro.domain

#默认日志  默认级别是 INFO,WARN,ERROR
#logging:
#  file: my.log
#  path: logs/
#  level.*: info

